<?php

namespace frontend\controllers;

use common\models\User;
use frontend\models\UserCreateForm;
use frontend\models\UserForm;
use Yii;
use yii\grid\GridView;
use yii\helpers\VarDumper;
use yii\web\Controller;
use yii\data\ArrayDataProvider;
use yii\widgets\ActiveForm;

/**
 * Class UserController
 * @package frontend\controllers
 */
class UserController extends Controller
{
    /**
     * @var \mongosoft\soapclient\Client
     */
    public $client;

    /**
     * @param $action
     * @return bool
     * @throws \yii\web\BadRequestHttpException
     */
    public function beforeAction($action)
    {
        $auth_key = Yii::$app->session->get('auth_key');
        if (!$auth_key) {
            Yii::$app->response->redirect(['/site/index']);
            return false;
        }

        return parent::beforeAction($action); // TODO: Change the autogenerated stub
    }

    /**
     * UserController constructor.
     * @param $id
     * @param $module
     * @param array $config
     */
    public function __construct($id, $module, $config = [])
    {
        parent::__construct($id, $module, $config);

        $this->client = new \mongosoft\soapclient\Client([
            'url' => 'http://soap-server.local.ew/index.php?r=api/soapApi',
        ]);
    }

    /**
     * @return array
     */
    public function behaviors()
    {
        return [];
    }

    /**
     * @return array
     */
    public function actions()
    {
        return [
            'error' => [
                'class' => 'Yii\web\ErrorAction',
            ]
        ];
    }

    /** GridView with all users (request from SOAP)
     *
     * @return string
     */
    public function actionIndex()
    {
        $model = null;
        $auth_key = Yii::$app->session->get('auth_key');
        $model = json_decode($this->client->getAllUsers($auth_key), true);

        $pageSize = Yii::$app->request->get('per-page', 5);

        $dataProvider = new ArrayDataProvider([
            'allModels' => $model['users'],
            'pagination' => [
                'pageSize' => $pageSize,
            ]
        ]);

        return $this->render('index', [
            'model' => $dataProvider,
        ]);
    }

    /**Returning a form to update a user
     *
     * @param $id
     *
     * @return string|\yii\web\Response
     */
    public function actionUpdate($id)
    {
        if (Yii::$app->request->isPost) {
            $this->client->updateUser(Yii::$app->session->get('auth_key'), $id, json_encode(Yii::$app->request->post('UserForm')));
            return $this->redirect('index.php?r=user/index');
        }
        $params = json_decode($this->client->getOneUser(Yii::$app->session->get('auth_key'), $id), true);
        $model = new UserForm();
        $model->setAttributes($params, false);

        return $this->render('update', [
            'model' => $model
        ]);
    }

    /** Returning a Dynamic ActiveForm to create users
     *
     * @return string|\yii\web\Response
     */
    public function actionCreate()
    {
        if (Yii::$app->request->isPost) {
            $this->client->createUsers(Yii::$app->session->get('auth_key'), json_encode(Yii::$app->request->post()));
            return $this->redirect('index.php?r=user/index');
        }

        $model = [new UserCreateForm()];

        return $this->render('create', [
            'model' => $model
        ]);
    }

    /** Action used with views/user/create to add dynamic forms
     *
     * @return string
     */
    public function actionForm()
    {
        return $this->renderAjax('form',[
            'form' => new ActiveForm(),
            'model' => new UserCreateForm(),
            'id' => Yii::$app->request->post('id')
        ]);
    }

    /** Action used to delete a user
     *
     * @return \yii\web\Response
     */
    public function actionDelete()
    {
        if (Yii::$app->request->isPost) {
            $this->client->deleteUser(Yii::$app->session->get('auth_key'), Yii::$app->request->get('id'));
        }
        return $this->redirect('index.php?r=user/index');

    }
}